#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-joda-time
Version  : 2.2
Release  : 1
URL      : https://repo1.maven.org/maven2/joda-time/joda-time/2.2/joda-time-2.2.jar
Source0  : https://repo1.maven.org/maven2/joda-time/joda-time/2.2/joda-time-2.2.jar
Source1  : https://repo1.maven.org/maven2/joda-time/joda-time/2.2/joda-time-2.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-joda-time-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-joda-time package.
Group: Data

%description data
data components for the mvn-joda-time package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/joda-time/e/2.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/joda-time/e/2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/joda-time/e/2.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/joda-time/e/2.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/joda-time/e/2.2/joda-time-2.2.jar
/usr/share/java/.m2/repository/joda-time/e/2.2/joda-time-2.2.pom
